import { NextRequest, NextResponse } from 'next/server';
import { supabaseServer } from '@/lib/supabaseServer';
import { normalizeProduct } from '@/lib/normalizeProduct'
import { normalizeStock } from '@/lib/stock'


export const runtime = 'nodejs'
export const dynamic = 'force-dynamic'

/* ===========================
   Helpers
=========================== */
function numOrNull(v: unknown): number | null {
    if (v === null || v === undefined || v === '') return null;
    const n = Number(v);
    return Number.isFinite(n) ? n : null;
}
function mustNumber(v: unknown, field = 'number'): number {
    const n = Number(v);
    if (!Number.isFinite(n)) {
        throw new Error(`Invalid ${field}`);
    }
    return n;
}
function normalizeUnitType(
    value: unknown
): 'per_unit' | 'per_kg' | null | undefined {
    if (value === 'per_unit' || value === 'per_kg') return value;
    if (value === null || typeof value === 'undefined') return value;
    throw new Error('Invalid unit_type');
}

/* ===========================
   GET /api/products
   Returns active products
=========================== */
export async function GET() {
    try {
        const svc = supabaseServer();
        const { data, error } = await svc
            .from('products')
            .select(
                'id,name,description,price,price_sale,unit_type,category_id,stock,stock_unlimited,image_url,images,is_active,deleted_at,created_at,qty_step'
            )
            .eq('is_active', true)        // <-- fix: use is_active
            .eq('archived', false)        // <-- fix: exclude archived products (blocked by DB trigger)
            .is('deleted_at', null)
            .order('created_at', { ascending: false });

        if (error) throw error;

        // Normalize numeric fields and avoid strings
        const items = (data ?? []).map((p: any) => ({
            ...p,
            price: mustNumber(p.price, 'price'),
            price_sale: p.price_sale == null ? null : mustNumber(p.price_sale, 'price_sale'),
            stock: numOrNull(p.stock),
            stock_unlimited: p.stock_unlimited === true,
            qty_step: p.qty_step == null ? null : Number(p.qty_step),
        }));

        return NextResponse.json(
            { items },
            { headers: { 'Cache-Control': 'no-store' } }
        );
    } catch (e: any) {
        return NextResponse.json({ error: e?.message ?? 'Errore' }, { status: 500 });
    }
}

/* ===========================
   POST /api/products
   Create a product.
   - SKU optional: if missing/empty, it is generated by the DB
   - Duplicate SKU -> 409
=========================== */
type NewProduct = {
    name: string;
    price: number | string;
    price_sale?: number | string | null;
    sku?: string | null;
    active?: boolean;      // legacy: map it to is_active
    is_active?: boolean;   // preferred
    description?: string | null;
    unit_type?: string | null;
    qty_step?: number | string | null;
    category_id?: string | null;
    image_url?: string | null;
    images?: any[] | null;
    stock?: number | string | null; // null = unlimited
};

export async function POST(req: NextRequest) {
    try {
        const body = (await req.json()) as NewProduct;

        if (!body?.name) {
            return NextResponse.json({ error: 'name is required' }, { status: 400 });
        }

        let price: number;
        try {
            price = mustNumber(body.price, 'price');
        } catch (err: any) {
            return NextResponse.json({ error: err.message }, { status: 400 });
        }

        // Normalize stock (real kg for per_kg, integer for per_unit)
        let stockValue: number | null = null;
        if (typeof body.stock !== 'undefined') {
            try {
                const unitType = normalizeUnitType(body.unit_type);
                stockValue = normalizeStock(unitType, body.stock);
            } catch (err: any) {
                return NextResponse.json({ error: err.message }, { status: 400 });
            }
        }

        const insert: any = {
            name: body.name,
            description: body.description ?? '',
            price,
            price_sale: numOrNull(body.price_sale),
            image_url: body.image_url ?? null,
            images: Array.isArray(body.images) ? body.images : null,
            unit_type: body.unit_type ?? null,
            category_id: body.category_id ?? null,
            stock: stockValue, // null = unlimited
            // prefer is_active; if not passed, default true
            is_active:
                typeof body.is_active === 'boolean'
                    ? body.is_active
                    : typeof body.active === 'boolean'
                        ? body.active
                        : true,
        };

        // SKU: if missing/empty, do not pass it (handled by DB)
        if (body.sku && body.sku.trim() !== '') {
            insert.sku = body.sku.trim();
        }

        if (typeof body.qty_step !== 'undefined') {
            if (body.qty_step === null || body.qty_step === '') {
                insert.qty_step = null;
            } else {
                let n: number;
                try {
                    n = mustNumber(body.qty_step, 'qty_step');
                } catch (err: any) {
                    return NextResponse.json({ error: err.message }, { status: 400 });
                }
                if (n <= 0) {
                    return NextResponse.json({ error: 'qty_step must be > 0' }, { status: 400 });
                }
                insert.qty_step = Math.round((n + Number.EPSILON) * 1000) / 1000;
            }
        }

        const svc = supabaseServer();
        const { data, error } = await svc.from('products').insert(insert).select('*').single();

        if (error) {
            const msg = String(error.message || error);
            if (msg.toLowerCase().includes('duplicate key') || msg.toLowerCase().includes('already exists')) {
                return NextResponse.json({ error: 'SKU already in use' }, { status: 409 });
            }
            return NextResponse.json({ error: msg }, { status: 500 });
        }

        // normalizza numerici anche in risposta
        const product = {
            ...data,
            price: mustNumber(data.price, 'price'),
            price_sale: data.price_sale == null ? null : mustNumber(data.price_sale, 'price_sale'),
            stock: numOrNull(data.stock),
            qty_step: numOrNull(data.qty_step),
        };

        return NextResponse.json({ product }, { status: 201 });
    } catch (e: any) {
        return NextResponse.json({ error: e?.message ?? 'Error saving product' }, { status: 500 });
    }
}

/* =======================================
   PATCH /api/products
   Update a product.
   - SKU immutable (immutable)
   - If sku is present in body -> 400
======================================= */
type UpdateProduct = {
    id: string;
    name?: string;
    price?: number | string;
    price_sale?: number | string | null;
    active?: boolean;      // legacy
    is_active?: boolean;
    description?: string | null;
    unit_type?: string | null;
    qty_step?: number | string | null;
    category_id?: string | null;
    image_url?: string | null;
    images?: any[] | null;
    stock?: number | string | null; // null = unlimited
    sku?: string | null;            // immutable
};

export async function PATCH(req: NextRequest) {
    try {
        const body = (await req.json()) as UpdateProduct;
        if (!body?.id) {
            return NextResponse.json({ error: 'id is required' }, { status: 400 });
        }

        if (typeof body.sku !== 'undefined') {
            return NextResponse.json({ error: 'SKU immutable' }, { status: 400 });
        }

        const { id, ...rest } = body;

        const update: Record<string, any> = {};
        if (typeof rest.name !== 'undefined') update.name = rest.name;
        if (typeof rest.description !== 'undefined') update.description = rest.description ?? '';
        if (typeof rest.price !== 'undefined') {
            try {
                update.price = mustNumber(rest.price, 'price');
            } catch (err: any) {
                return NextResponse.json({ error: err.message }, { status: 400 });
            }
        }
        if (typeof rest.price_sale !== 'undefined') {
            update.price_sale = numOrNull(rest.price_sale);
        }
        if (typeof rest.image_url !== 'undefined') update.image_url = rest.image_url ?? null;
        if (typeof rest.images !== 'undefined') update.images = Array.isArray(rest.images) ? rest.images : null;
        if (typeof rest.unit_type !== 'undefined') update.unit_type = rest.unit_type ?? null;
        if (typeof rest.category_id !== 'undefined') update.category_id = rest.category_id ?? null;
        if (typeof rest.qty_step !== 'undefined') {
            if (rest.qty_step === null || rest.qty_step === '') {
                update.qty_step = null;
            } else {
                let n: number;
                try {
                    n = mustNumber(rest.qty_step, 'qty_step');
                } catch (err: any) {
                    return NextResponse.json({ error: err.message }, { status: 400 });
                }
                if (n <= 0) {
                    return NextResponse.json({ error: 'qty_step must be > 0' }, { status: 400 });
                }
                update.qty_step = Math.round((n + Number.EPSILON) * 1000) / 1000;
            }
        }

        // Normalize stock (real kg for per_kg, integer for per_unit)
        if (typeof rest.stock !== 'undefined') {
            // Retrieve current unit_type if not modified
            let unitType: 'per_unit' | 'per_kg' | null | undefined;
            if (rest.unit_type === undefined) {
                const svc = supabaseServer();
                const { data: current } = await svc
                    .from('products')
                    .select('unit_type')
                    .eq('id', id)
                    .single();
                unitType = normalizeUnitType(current?.unit_type ?? null);
            } else {
                try {
                    unitType = normalizeUnitType(rest.unit_type);
                } catch (err: any) {
                    return NextResponse.json({ error: err.message }, { status: 400 });
                }
            }
            try {
                update.stock = normalizeStock(unitType, rest.stock);
            } catch (err: any) {
                return NextResponse.json({ error: err.message }, { status: 400 });
            }
        }

        // map legacy active -> is_active
        if (typeof rest.is_active === 'boolean') {
            update.is_active = rest.is_active;
        } else if (typeof rest.active === 'boolean') {
            update.is_active = rest.active;
        }

        if (Object.keys(update).length === 0) {
            // nothing to update
            return NextResponse.json({ product: null });
        }

        const svc = supabaseServer();
        const { data, error } = await svc
            .from('products')
            .update(update)
            .eq('id', id)
            .select('*')
            .single();

        if (error) throw error;

        const product = {
            ...data,
            price: mustNumber(data.price, 'price'),
            price_sale: data.price_sale == null ? null : mustNumber(data.price_sale, 'price_sale'),
            stock: numOrNull(data.stock),
            qty_step: numOrNull(data.qty_step),
        };

        return NextResponse.json({ product });
    } catch (e: any) {
        return NextResponse.json({ error: e?.message ?? 'Errore aggiornamento prodotto' }, { status: 500 });
    }
}
